- name: Delete on Openstack
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Delete an instance
    os_server:
         validate_certs: False
         state: absent
         name: '{{handlerid}}' 
         image: '{{image_id}}'
         key_name: '{{key_name}}'
         network: '{{private_network}}'
         timeout: 200
         flavor: 2
         wait: yes
  - name: Delete from galaxy.ini
    shell: crudini --del /home/ubuntu/galaxy/config/galaxy.ini server:{{handlerid}}
  - name: Edit job_conf
    shell: sed -i '/<handler id="{{handlerid}}" tags="handlers"\/>/d' /home/ubuntu/galaxy/config/job_conf.xml
  - name: Stop web server
    shell: cd /home/ubuntu/galaxy/; python /home/ubuntu/galaxy/scripts/paster.py serve config/galaxy.ini --server-name=web0 --pid-file=/home/ubuntu/galaxy/web0.pid --log-file=/home/ubuntu/galaxy/web0.log --stop-daemon
  - name: Restart web server
    shell: cd /home/ubuntu/galaxy/; python /home/ubuntu/galaxy/scripts/paster.py serve config/galaxy.ini --server-name=web0 --pid-file=/home/ubuntu/galaxy/web0.pid --log-file=/home/ubuntu/galaxy/web0.log --daemon 
